name: dijon
channels:
  - conda-forge
dependencies:
  - orjson
  - pip
  - pydantic
  - pytest
  - python=3.12
  - pyyaml
  - ruff
  - setuptools
  - typer
  - wheel
  - pip:
    - dijon==0.1.0

prefix: "/opt/homebrew/Caskroom/miniforge/base/envs/dijon"
